# Generated by Django 5.1 on 2024-08-30 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
