# Generated by Django 5.1 on 2024-08-31 05:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_qunatity_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellinguser',
            name='seller_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.sellinguser'),
        ),
    ]
