# Generated by Django 5.1 on 2024-08-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_is_seller_sellinguser_seller_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_seller',
        ),
        migrations.AddField(
            model_name='sellinguser',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
