# Generated by Django 5.1 on 2024-08-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sellinguser_seller_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinguser',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sellinguser',
            name='seller_type',
            field=models.CharField(blank=True, choices=[('Manufacturer', 'Manufacturer'), ('Private', 'Private'), ('Reseller', 'Reseller')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellinguser',
            name='seller_uid',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
    ]
