# Generated by Django 5.1 on 2024-09-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sellinguser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prod_listed',
            field=models.IntegerField(default=0),
        ),
    ]
